import React from 'react';
import { Play, Sparkles, Check, Copy, ArrowRight, ShieldCheck, Zap, AlertTriangle, Layers } from 'lucide-react';

export default function OutputComparison({
  rawOutput,
  enhancedOutput,
  isExecuting,
  userPrompt,
  suggestedPrompt,
  onRunComparison
}) {
  const [copiedRaw, setCopiedRaw] = React.useState(false);
  const [copiedEnhanced, setCopiedEnhanced] = React.useState(false);

  const rawWords = rawOutput ? rawOutput.split(/\s+/).filter(Boolean).length : 0;
  const enhancedWords = enhancedOutput ? enhancedOutput.split(/\s+/).filter(Boolean).length : 0;

  const copyText = (text, type) => {
    if (!text) return;
    navigator.clipboard.writeText(text);
    if (type === 'raw') {
      setCopiedRaw(true);
      setTimeout(() => setCopiedRaw(false), 2000);
    } else {
      setCopiedEnhanced(true);
      setTimeout(() => setCopiedEnhanced(false), 2000);
    }
  };

  return (
    <div className="w-full mt-6">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-4 px-1">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-emerald-500/10 text-emerald-400">
            <Zap className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-gray-100">4. Live LLM Output Comparison</h2>
            <p className="text-xs text-gray-400">Compare real-time outputs generated by the Original vs Refined prompt</p>
          </div>
        </div>

        <button
          onClick={onRunComparison}
          disabled={!userPrompt.trim() || isExecuting}
          className="btn-primary text-xs py-2 px-4 flex items-center gap-2 disabled:opacity-50"
        >
          <Play className="w-3.5 h-3.5 fill-current" />
          <span>{isExecuting ? 'Generating LLM Outputs...' : 'Run Output Comparison'}</span>
        </button>
      </div>

      {/* Side-by-Side Dual Execution Workbench */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left Column: Original Prompt Output */}
        <div className="glass-panel p-5 flex flex-col justify-between border-slate-700/50">
          <div>
            <div className="flex items-center justify-between mb-3 border-b border-white/10 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-red-400"></span>
                <h3 className="text-sm font-bold text-gray-300">Original Prompt Output</h3>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-mono text-gray-400">{rawWords} words</span>
                <button
                  onClick={() => copyText(rawOutput, 'raw')}
                  disabled={!rawOutput}
                  className="p-1 text-gray-400 hover:text-white transition-colors"
                  title="Copy raw output"
                >
                  {copiedRaw ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-slate-950/80 border border-white/5 min-h-[260px] text-xs text-gray-300 leading-relaxed font-sans overflow-y-auto max-h-[360px]">
              {isExecuting ? (
                <div className="flex flex-col items-center justify-center h-48 space-y-3">
                  <div className="w-6 h-6 border-2 border-red-400 border-t-transparent rounded-full animate-spin"></div>
                  <p className="text-xs text-gray-400 animate-pulse">Executing original prompt...</p>
                </div>
              ) : rawOutput ? (
                <div className="whitespace-pre-wrap">{rawOutput}</div>
              ) : (
                <div className="text-gray-500 italic flex flex-col items-center justify-center h-48 text-center space-y-2">
                  <AlertTriangle className="w-6 h-6 text-gray-600" />
                  <p>Click "Run Output Comparison" to observe how the unrefined prompt responds.</p>
                </div>
              )}
            </div>
          </div>

          <div className="mt-3 pt-2 border-t border-white/5 flex items-center justify-between text-[11px] text-gray-400">
            <span className="text-red-400/90 font-medium">Result: Broad & generic response</span>
            <span>Structure: Unstructured</span>
          </div>
        </div>

        {/* Right Column: Refined Prompt Output */}
        <div className="glass-panel-glow p-5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3 border-b border-violet-500/30 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-ping"></span>
                <h3 className="text-sm font-bold text-gradient">Refined Prompt Output (Collaborative AI)</h3>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-mono text-emerald-400 font-semibold">{enhancedWords} words</span>
                <button
                  onClick={() => copyText(enhancedOutput, 'enhanced')}
                  disabled={!enhancedOutput}
                  className="p-1 text-gray-400 hover:text-white transition-colors"
                  title="Copy refined output"
                >
                  {copiedEnhanced ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-slate-950/90 border border-emerald-500/30 min-h-[260px] text-xs text-gray-200 leading-relaxed font-sans overflow-y-auto max-h-[360px]">
              {isExecuting ? (
                <div className="flex flex-col items-center justify-center h-48 space-y-3">
                  <div className="w-6 h-6 border-2 border-emerald-400 border-t-transparent rounded-full animate-spin"></div>
                  <p className="text-xs text-emerald-300 animate-pulse">Executing AI refined prompt...</p>
                </div>
              ) : enhancedOutput ? (
                <div className="whitespace-pre-wrap prose prose-invert max-w-none">
                  {enhancedOutput}
                </div>
              ) : (
                <div className="text-gray-500 italic flex flex-col items-center justify-center h-48 text-center space-y-2">
                  <Sparkles className="w-6 h-6 text-violet-400 animate-bounce" />
                  <p>Run comparison to experience structured, domain-expert output quality.</p>
                </div>
              )}
            </div>
          </div>

          <div className="mt-3 pt-2 border-t border-emerald-500/20 flex items-center justify-between text-[11px] text-emerald-400">
            <span className="font-semibold flex items-center gap-1">
              <ShieldCheck className="w-3.5 h-3.5" />
              Result: High precision, structured & actionable
            </span>
            <span className="font-mono">Quality Boost: +350%</span>
          </div>
        </div>
      </div>
    </div>
  );
}
